version: "3.3"
services:
    server:
        build: server/
        command: sh -c "./server 12347"
        network_mode: host
        image: mgt-server
    client:
        build: client/
        command: sh -c "./client localhost:12347 tests/*"
        network_mode: host
        image: mgt-client
        depends_on:
            - server
